FactoryBot.define do
  factory :point_of_interest do
    point { build :point }
    name { "point_of_interest" }
    description { "POI generated by factory" }
    after(:build) do |point_of_interest|
      point_of_interest.image.attach(
        io: File.open("spec/fixture_files/placeholder_person.png"),
        filename: 'test.png',
        content_type: 'image/png'
      )
    end
  end
end
