# Rubocop configuration, see https://docs.rubocop.org/rubocop/configuration.html

require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

# opt-in to new rules (cops)
AllCops:
  NewCops: enable

#
# Specific excludes & includes
#

# Using instance variables might make tests fail based on their order.
RSpec/InstanceVariable:
  AssignmentOnly: true
  Enabled: true

# Ignore LineLength for config files (e.g. with long secret strings)
Layout/LineLength:
  Exclude:
    - "config/**/*"

# Ignore 'Use $stdout instead of STDOUT' in configs
Style/GlobalStdStream:
  Exclude:
    - "config/**/*"

# Ignore "Block has too many lines" for specs, `RSpec.describe` blocks can be long
Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "config/**/*"

# Configs can complex options, may need custom layout
Layout/ArgumentAlignment:
  Exclude:
    - "config/**/*"
Layout/HashAlignment:
  Exclude:
    - "config/**/*"

# Only check "Missing top-level class documentation comment" for models
Style/Documentation:
  Include:
    - "app/models/*.rb"

# The autogenerated file has a large comment block. So be it.
Style/BlockComments:
  Exclude:
    - "spec/spec_helper.rb"

# Okay for special controllers interacting with devise
Style/ClassAndModuleChildren:
  Exclude:
    - app/controllers/users/*.rb

#
# Ignoring entire rules
#

# Okay to have long examples
RSpec/ExampleLength:
  Enabled: false

# Okay to have more than one expectation in a single block
RSpec/MultipleExpectations:
  Enabled: false

# Okay to have empty lines around code blocks
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

# Ignore "Missing frozen string literal comment"
Style/FrozenStringLiteralComment:
  Enabled: false

# Ignore "Gems should be sorted in an alphabetical order within their section of the Gemfile"
Bundler/OrderedGems:
  Enabled: false

# Okay to have strings with "" instead of '', even when not doing interpolation
Style/StringLiterals:
  Enabled: false

# Okay to have space in array definitions: [ 'a','b','c' ]
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

# Okay to use normal array syntax [:a, :b, :c] for symbols instead of %i or %I
Style/SymbolArray:
  Enabled: false

# Okay to use Rails.root.join('tmp', 'caching-dev.txt')
Rails/FilePath:
  Enabled: false

Metrics/MethodLength:
  Max: 20

# Okay to use has_and_belongs_to_many for many-to-many relationships
Rails/HasAndBelongsToMany:
  Enabled: false
