require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/chairs", type: :request do

  # Chair. As you add validations to Chair, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      Chair.create! valid_attributes
      get chairs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      chair = Chair.create! valid_attributes
      get chair_url(chair)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_chair_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      chair = Chair.create! valid_attributes
      get edit_chair_url(chair)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Chair" do
        expect do
          post chairs_url, params: { chair: valid_attributes }
        end.to change(Chair, :count).by(1)
      end

      it "redirects to the created chair" do
        post chairs_url, params: { chair: valid_attributes }
        expect(response).to redirect_to(chair_url(Chair.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Chair" do
        expect do
          post chairs_url, params: { chair: invalid_attributes }
        end.to change(Chair, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post chairs_url, params: { chair: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested chair" do
        chair = Chair.create! valid_attributes
        patch chair_url(chair), params: { chair: new_attributes }
        chair.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the chair" do
        chair = Chair.create! valid_attributes
        patch chair_url(chair), params: { chair: new_attributes }
        chair.reload
        expect(response).to redirect_to(chair_url(chair))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        chair = Chair.create! valid_attributes
        patch chair_url(chair), params: { chair: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested chair" do
      chair = Chair.create! valid_attributes
      expect do
        delete chair_url(chair)
      end.to change(Chair, :count).by(-1)
    end

    it "redirects to the chairs list" do
      chair = Chair.create! valid_attributes
      delete chair_url(chair)
      expect(response).to redirect_to(chairs_url)
    end
  end
end
