require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/data_problems", type: :request do

  # DataProblem. As you add validations to DataProblem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip("Add a hash of attributes valid for your model")
  end

  let(:invalid_attributes) do
    skip("Add a hash of attributes invalid for your model")
  end

  describe "GET /index" do
    it "renders a successful response" do
      DataProblem.create! valid_attributes
      get data_problems_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      data_problem = DataProblem.create! valid_attributes
      get data_problem_url(data_problem)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_data_problem_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      data_problem = DataProblem.create! valid_attributes
      get edit_data_problem_url(data_problem)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DataProblem" do
        expect do
          post data_problems_url, params: { data_problem: valid_attributes }
        end.to change(DataProblem, :count).by(1)
      end

      it "redirects to the created data_problem" do
        post data_problems_url, params: { data_problem: valid_attributes }
        expect(response).to redirect_to(data_problem_url(DataProblem.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DataProblem" do
        expect do
          post data_problems_url, params: { data_problem: invalid_attributes }
        end.to change(DataProblem, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post data_problems_url, params: { data_problem: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) do
        skip("Add a hash of attributes valid for your model")
      end

      it "updates the requested data_problem" do
        data_problem = DataProblem.create! valid_attributes
        patch data_problem_url(data_problem), params: { data_problem: new_attributes }
        data_problem.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the data_problem" do
        data_problem = DataProblem.create! valid_attributes
        patch data_problem_url(data_problem), params: { data_problem: new_attributes }
        data_problem.reload
        expect(response).to redirect_to(data_problem_url(data_problem))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        data_problem = DataProblem.create! valid_attributes
        patch data_problem_url(data_problem), params: { data_problem: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested data_problem" do
      data_problem = DataProblem.create! valid_attributes
      expect do
        delete data_problem_url(data_problem)
      end.to change(DataProblem, :count).by(-1)
    end

    it "redirects to the data_problems list" do
      data_problem = DataProblem.create! valid_attributes
      delete data_problem_url(data_problem)
      expect(response).to redirect_to(data_problems_url)
    end
  end
end
