 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/person_urls", type: :request do
  
  # PersonUrl. As you add validations to PersonUrl, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PersonUrl.create! valid_attributes
      get person_urls_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      person_url = PersonUrl.create! valid_attributes
      get person_url_url(person_url)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_person_url_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      person_url = PersonUrl.create! valid_attributes
      get edit_person_url_url(person_url)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PersonUrl" do
        expect {
          post person_urls_url, params: { person_url: valid_attributes }
        }.to change(PersonUrl, :count).by(1)
      end

      it "redirects to the created person_url" do
        post person_urls_url, params: { person_url: valid_attributes }
        expect(response).to redirect_to(person_url_url(PersonUrl.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PersonUrl" do
        expect {
          post person_urls_url, params: { person_url: invalid_attributes }
        }.to change(PersonUrl, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post person_urls_url, params: { person_url: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested person_url" do
        person_url = PersonUrl.create! valid_attributes
        patch person_url_url(person_url), params: { person_url: new_attributes }
        person_url.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the person_url" do
        person_url = PersonUrl.create! valid_attributes
        patch person_url_url(person_url), params: { person_url: new_attributes }
        person_url.reload
        expect(response).to redirect_to(person_url_url(person_url))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        person_url = PersonUrl.create! valid_attributes
        patch person_url_url(person_url), params: { person_url: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested person_url" do
      person_url = PersonUrl.create! valid_attributes
      expect {
        delete person_url_url(person_url)
      }.to change(PersonUrl, :count).by(-1)
    end

    it "redirects to the person_urls list" do
      person_url = PersonUrl.create! valid_attributes
      delete person_url_url(person_url)
      expect(response).to redirect_to(person_urls_url)
    end
  end
end
